"""Make Paper.level nullable and add default

Revision ID: 049e9ae826c6
Revises: 3ae79a5d68c0
Create Date: 2025-08-14 02:07:37.861286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '049e9ae826c6'
down_revision: Union[str, Sequence[str], None] = '3ae79a5d68c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('level', sa.String(), server_default='Foundation', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'level')
    # ### end Alembic commands ###
